[Details]
Icon = "icon.png"
Name = "FyClip"
ID = "com.sarwar.fyclip"
Version = "1.7.1"
Build = 16

[LinuxAndBSD]
GenericName = "Clipboard Manager"
Categories = ["Utility"]
Comment = "Advanced Clipboard Manager"

[Migrations]
fyneDo = true
