[Details]
Icon = "icon.png"
Name = "FyClip"
ID = "com.sarwar.fyclip"
Version = "2.0.0"
Build = 1

[LinuxAndBSD]
GenericName = "Clipboard Manager"
Categories = ["Utility"]
Comment = "Advanced Clipboard Manager"

[Migrations]
fyneDo = true
