[Details]
Icon = "icon.png"
Name = "FyClip"
ID = "com.sarwar.fyclip"
Version = "1.5.0"
Build = 2

[LinuxAndBSD]
GenericName = "Clipboard Manager"
Categories = ["Utility"]
Comment = "Advanced Clipboard Manager"

[Migrations]
fyneDo = true
